### ISSUE TITLE
EPIC: Write code to replicate conversation about Travelling with Conviction

### ISSUE THREAD

**Issue by m4v15** [InFact-coop/Unlock#14]
relates #4 #1 

Current plan is to build a chat that is similar in usage to other chats; namely Chip, Babylon, Intercom - i.e. be asked questions and answer them, without too much of a free chat element, but also with keyword recognition. Almost a form disguised as a chat bot. Will follow a logic tree/flow chart type thing (#11) 

Features:
- [x] Overall the flow will take a user through a series of questions to find out what they need to do to travel to the US.
- [x] Want to see the previous messages displayed as in chats, above the input
- [x] Be able to input either by clicking an option, or typing text
- [x] Get back a response relevant to what was clicked, and then be given more options
- [x] Will be given links to the relevant Infohub page at the end, or phone number
